receivers:
    opencensus:
        address: "127.0.0.1:55678"

exporters:  
    lightstep:
        satellite_host: "localhost"
        satellite_port: 8360
        satellite_use_plaintext: true
        access_token: "none"

zpages:
    port: 55679
